pipelines:
  branches:
    master:
      - step:
          script: # Modify the commands below to build your repository.
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"dist/master.zip"