apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.settings.name }}-wordpress
  labels:
    app.kubernetes.io/name: {{ .Values.settings.name }}-wordpress
    app.kubernetes.io/part-of: {{ .Values.settings.name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.settings.name }}-wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.settings.name }}-wordpress
        app.kubernetes.io/part-of: {{ .Values.settings.name }}
        helm.sh/chart: {{ include "chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      volumes:
        - name: {{ .Values.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volume.claimName }}

      containers:
        - name: {{ .Values.settings.name }}-wordpress
          image: "{{ .Values.settings.registryBase }}/{{ .Values.settings.openwebconcept }}:4.8"
          imagePullPolicy: {{ .Values.settings.pullPolicy }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: {{ .Values.volume.name }}
              mountPath: wordpress
              subPath: /bitnami/wordpress
          env:
            - name: MARIADB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.settings.name }}-configmap
                  key: mariadb-host
            - name: MARIADB_PORT_NUMBER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.settings.name }}-configmap
                  key: mariadb-port
            - name: WORDPRESS_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.settings.name }}-configmap
                  key: mariadb-name
            - name: WORDPRESS_DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.settings.name }}-configmap
                  key: mariadb-user
            - name: WORDPRESS_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "wordpress.databaseSecretName" . }}
                  key: mariadb-password
          resources:
  {{ toYaml .Values.resources | indent 12 }}
  {{- if .Values.nodeSelector }}
nodeSelector:
  {{ toYaml .Values.nodeSelector | indent 8 }}
  {{- end }}
