apiVersion: v1
entries:
  owc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-12-16T12:51:08.2293789+01:00"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 17bbc9878769bb310296dcbaf3d42a50e1ae66cd8aacc099c4b22bb2098f5515
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: owc
    urls:
    - owc-0.1.0.tgz
    version: 0.1.0
generated: "2020-12-16T12:51:08.2233079+01:00"
