apiVersion: v1
entries:
  owc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-12-16T12:41:13.8223892+01:00"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: a23bda7aa723e7995f7aea082f00e8ebfde934a40a71f059a02376d11c1a9fd2
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: owc
    urls:
    - owc-0.1.0.tgz
    version: 0.1.0
generated: "2020-12-16T12:41:13.8178851+01:00"
